# Generated by Django 6.1.1 on 2026-10-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlemanpackage',
            name='resolution_template',
            field=models.TextField(blank=True, default='', help_text='Wzór uchwały intencyjnej lub zarządzenia'),
        ),
    ]
