export type Solution = {
  availability: string;
  categories: string[];
  description: string;
  image: { alt: string; src: string };
  locality: string;
  matchScore: number;
  organization: string;
  slug: string;
  summary: string;
  title: string;
};

export const solutions: Solution[] = [
  {
    slug: "bawita-tablica-sensoryczna",
    title: "BaWita – Mobilna sensoryczna tablica aktywizująca",
    organization: "Fundacja Rozwoju Terapii Zajęciowej (Nowy Sącz)",
    locality: "Powiat nowosądecki i Małopolska",
    categories: ["Dla seniorów", "Terapia sensoryczna"],
    availability: "Gotowe do wdrożenia w gminach",
    matchScore: 98,
    summary: "Przenośny zestaw stymulacji sensorycznej i pamięciowej dla seniorów i osób z chorobami otępiennymi.",
    description: "BaWita to innowacyjny zestaw modułowych elementów sensoryczno-manualnych, zaprojektowany z myślą o osobach z otępieniem, chorobą Alzheimera oraz seniorach doświadczających izolacji. Został opracowany przez zespół terapeutyczny Inkubatora ROPS Kraków. Może być transportowany w poręcznej walizce do domu podopiecznego lub świetlicy wiejskiej przez asystenta CUS.",
    image: { src: "/discovery/recommendation-digital-skills.jpg", alt: "BaWita – sensoryczna tablica aktywizująca dla seniorów" },
  },
  {
    slug: "senior-cuder-gra-integracyjna",
    title: "Senior CUDER – Gra integracyjno-aktywizująca",
    organization: "Stowarzyszenie Dialog Społeczny",
    locality: "Małopolska (kluby seniora i sołectwa)",
    categories: ["Dla seniorów", "Zdrowie psychiczne"],
    availability: "Dostępne bezpłatne zestawy dla NGO i CUS",
    matchScore: 96,
    summary: "Planszowa i plenerowa metoda integracji międzypokoleniowej oraz przeciwdziałania depresji i osamotnieniu.",
    description: "Senior CUDER (Ciało, Umysł, Duch, Emocje, Relacje) to holistyczna metoda pracy grupowej. Pozwala osobom starszym w bezpieczny sposób rozmawiać o trudnych emocjach, stracie i samotności, jednocześnie budując nowe relacje sąsiedzkie w klubach seniora i sołectwach.",
    image: { src: "/discovery/challenge-aging.jpg", alt: "Seniorzy grający w grę integracyjną Senior CUDER" },
  },
  {
    slug: "organizator-spolecznosci-lokalnej-cus",
    title: "Organizator Społeczności Lokalnej (OSL) w CUS",
    organization: "Centrum Usług Społecznych w Myślenicach",
    locality: "Powiat myślenicki i cała Małopolska",
    categories: ["Dla dzieci, młodzieży i rodziny", "Usługi społeczne"],
    availability: "Certyfikowany standard ROPS",
    matchScore: 97,
    summary: "Metoda animacji sąsiedzkiej aktywizująca mieszkańców do samopomocy i tworzenia lokalnych grup wsparcia.",
    description: "Model wdrożony i przetestowany m.in. w Centrum Usług Społecznych w Myślenicach. Zamiast czekać na zgłoszenia zasiłkowe, organizator wychodzi w teren, mapuje potencjał sołectw i wspiera powstawanie oddolnych inicjatyw rodzinnych i sąsiedzkich.",
    image: { src: "/discovery/challenge-social-services.jpg", alt: "Spotkanie organizatora społeczności lokalnej z mieszkańcami" },
  },
  {
    slug: "modularne-lazienki-dostepne",
    title: "Modularne łazienki dostępne – Szybki pakiet adaptacyjny",
    organization: "Fundacja Architektura Bez Barier",
    locality: "Powiat gorlicki i Małopolska",
    categories: ["Dla osób o ograniczonej mobilności", "Dostępność architektoniczna"],
    availability: "Montaż w 3 godziny bez kucia kafli",
    matchScore: 94,
    summary: "System bezinwazyjnych, demontowalnych uchwytów i podestów likwidujących bariery w wiejskich domach seniorów.",
    description: "Wielu seniorów w Małopolsce mieszka w domach z głębokimi wannami i wysokimi progami. Modularny pakiet pozwala w 3 godziny przekształcić łazienkę bez kucia płytek i kosztownych remontów, z możliwością późniejszego przeniesienia lub zwrotu do CUS.",
    image: { src: "/discovery/recommendation-peer-support.jpg", alt: "Modularne uchwyty i wyposażenie bezpiecznej łazienki" },
  },
  {
    slug: "straznik",
    title: "Strażnik – Osobisty asystent dźwiękowy dla niesłyszących",
    organization: "Politechnika Krakowska & AGH",
    locality: "Kraków i subregion tarnowski",
    categories: ["Dla osób z niepełnosprawnością sensoryczną", "Nowe technologie"],
    availability: "Trwają zapisy do programu pilotażowego",
    matchScore: 93,
    summary: "Opaska wibracyjna i aplikacja mobilna rozpoznająca kluczowe dźwięki otoczenia (alarm, dzwonek, klakson).",
    description: "Strażnik to inteligentny system ostrzegania dla osób niesłyszących i słabosłyszących. Opaska wibrująca z mikrofonem kierunkowym analizuje fale dźwiękowe i informuje użytkownika o sygnałach alarmowych, dzwonku do drzwi czy płaczu dziecka, drastycznie podnosząc bezpieczeństwo w domu i przestrzeni publicznej.",
    image: { src: "/discovery/challenge-digital-inclusion.jpg", alt: "Opaska wibracyjna Strażnik dla osób niesłyszących" },
  },
  {
    slug: "kawiarenka-naprawcza",
    title: "Kawiarenka Naprawcza – Punkt wymiany umiejętności",
    organization: "Fundacja Aktywna Małopolska (Tarnów)",
    locality: "Tarnów i gminy ościenne",
    categories: ["Dla rynku pracy", "Ekologia i integracja"],
    availability: "Otwarte warsztaty w każdą sobotę",
    matchScore: 92,
    summary: "Otwarte warsztaty, gdzie seniorzy-majsterkowicze uczą młodzież naprawy sprzętu, budując relacje i redukując odpady.",
    description: "Kawiarenka Naprawcza (Repair Cafe) łączy cele ekologiczne z włączeniem społecznym i reintegracją zawodową. Seniorzy odzyskują poczucie sprawczości, a młodzież zdobywa praktyczne kompetencje techniczne i rzemieślnicze pod okiem mentorów.",
    image: { src: "/discovery/recommendation-community-garden.jpg", alt: "Senior i młodzież wspólnie naprawiający sprzęt w kawiarence" },
  },
  {
    slug: "komix-zyciowy",
    title: "koMIX życiowy – Dialog z młodzieżą w kryzysie",
    organization: "Fundacja Po Drugie",
    locality: "Małopolska (szkoły i poradnie)",
    categories: ["Dla dzieci, młodzieży i rodziny", "Zdrowie psychiczne"],
    availability: "Zestawy kart dla szkół i psychologów",
    matchScore: 95,
    summary: "Karty komiksowe ułatwiające pedagogom i psychologom rozmowę z nastolatkami o emocjach, depresji i uzależnieniach.",
    description: "koMIX życiowy to seria autorskich kart graficznych przedstawiających realistyczne dylematy dorastania. Młodzież poprzez metafory komiksowe otwiera się na rozmowę o presji rówieśniczej, hejcie w internecie, samotności oraz konfliktach rodzinnych.",
    image: { src: "/discovery/challenge-mental-health.jpg", alt: "Karty narracyjne koMIX życiowy dla młodzieży" },
  },
  {
    slug: "paszport-pacjenta-z-choroba-rzadka",
    title: "Paszport pacjenta z chorobą rzadką",
    organization: "Krajowe Forum na Rzecz Terapii Chorób Rzadkich",
    locality: "Kraków i szpitale Małopolski",
    categories: ["Dla zdrowia i medycyny", "Ochrona zdrowia"],
    availability: "Bezpłatne wydanie karty przez lekarza",
    matchScore: 96,
    summary: "Karta ratunkowa i profil cyfrowy z kodem QR skracający czas diagnozy i ratujący życie na SOR.",
    description: "Pacjenci z chorobami rzadkimi w sytuacji nagłego zagrożenia życia często otrzymują niewłaściwe leki na SOR. Paszport Pacjenta zawiera zweryfikowany przez klinikę protokół postępowania ratunkowego, listę leków zakazanych oraz całodobowy telefon do lekarza prowadzącego.",
    image: { src: "/discovery/recommendation-digital-skills.jpg", alt: "Karta ratunkowa Paszport Pacjenta z kodem QR" },
  },
  {
    slug: "merkury-symulator-samoobslugowy",
    title: "Merkury – Symulator samoobsługowy biletomatów i kas",
    organization: "Spółdzielnia Socjalna Cyfrowy Horyzont",
    locality: "Kraków, Tarnów, Nowy Sącz (WTZ)",
    categories: ["Dla osób z niepełnosprawnością intelektualną", "Dostępność cyfrowa"],
    availability: "Testy w placówkach WTZ",
    matchScore: 91,
    summary: "Interaktywny trenażer ułatwiający naukę korzystania z biletomatów, bankomatów i kas samoobsługowych bez stresu.",
    description: "Merkury to oprogramowanie połączone z fizycznym dotykowym ekranem treningowym, które symuluje realne miejskie kasy i biletomaty. Umożliwia osobom w spektrum autyzmu i z niepełnosprawnością intelektualną bezstresowe ćwiczenie zakupów i przełamanie bariery lęku.",
    image: { src: "/discovery/challenge-digital-inclusion.jpg", alt: "Ekran dotykowy symulatora samoobsługowego Merkury" },
  },
  {
    slug: "szlakiem-ludzi-bezdomnych",
    title: "Szlakiem ludzi bezdomnych – Mobilny punkt wsparcia",
    organization: "Dzieło Pomocy św. Ojca Pio",
    locality: "Aglomeracja krakowska",
    categories: ["Dla osób w kryzysie bezdomności", "Wsparcie doraźne"],
    availability: "Dyżury codzienne w terenie",
    matchScore: 93,
    summary: "Specjalistyczny ambulans oferujący doraźną pomoc medyczną, pralnię, odzież i kontakt ze streetworkerem.",
    description: "Wielu ludzi w kryzysie bezdomności unika tradycyjnych schronisk i noclegowni z lęku przed odrzuceniem. Mobilny punkt dociera na dworce, koczowiska i pustostany, oferując bezpieczną kąpiel, opatrunek pielęgniarski oraz zaufany kontakt ze streetworkerem, otwierając drogę do wyjścia z kryzysu.",
    image: { src: "/discovery/challenge-social-services.jpg", alt: "Mobilny ambulans pomocy osobom w kryzysie bezdomności" },
  },
  {
    slug: "hear-it",
    title: "Hear IT – Kursy programowania i cyfryzacji w PJM",
    organization: "Inkubator Dostępności Cyfrowej & PJM",
    locality: "Cała Małopolska (online)",
    categories: ["Dla osób z niepełnosprawnością sensoryczną", "Edukacja cyfrowa"],
    availability: "Bezpłatne nabory co kwartał",
    matchScore: 94,
    summary: "Dostępna platforma e-learningowa prowadzona w Polskim Języku Migowym przygotowująca głuchych do pracy w IT.",
    description: "Hear IT przełamuje barierę językową w kształceniu zawodowym. Oferuje kursy testowania oprogramowania, analizy danych i tworzenia stron www z wykładami natywnych głuchych lektorów PJM oraz napisami dla niesłyszących. Ponad 60 absolwentów znalazło już pracę w branży IT.",
    image: { src: "/discovery/challenge-digital-inclusion.jpg", alt: "Lektor migający w Polskim Języku Migowym podczas kursu IT" },
  },
  {
    slug: "health-guide-pl",
    title: "Health Guide PL – Przewodnik po opiece medycznej",
    organization: "Centrum Dialogu Wielokulturowego",
    locality: "Kraków i powiaty Małopolski",
    categories: ["Dla cudzoziemców", "Zdrowie"],
    availability: "Aplikacja i informatory w urzędach",
    matchScore: 90,
    summary: "Wielojęzyczny asystent cyfrowy i piktograficzny informator po systemie POZ i NFZ dla migrantów i uchodźców.",
    description: "Health Guide PL tłumaczy skomplikowane procedury publicznej opieki zdrowotnej w Polsce na język ukraiński, angielski i hiszpański. Zawiera wzory dialogów z rejestracją, słownik dolegliwości i interaktywną mapę przychodni w Małopolsce świadczących pomoc bezpłatnie.",
    image: { src: "/discovery/recommendation-digital-skills.jpg", alt: "Wielojęzyczny przewodnik medyczny Health Guide PL" },
  },
];

export function getSolution(slug: string) {
  return solutions.find((solution) => solution.slug === slug);
}
